spring.application.name=wallet-r2
server.port=${PORT:8080}
server.shutdown=graceful

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/wallet}
spring.datasource.username=${DB_USER:wallet}
spring.datasource.password=${DB_PASSWORD:wallet}
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:20}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:2}
spring.datasource.hikari.connection-timeout=5000

spring.flyway.enabled=true
spring.flyway.validate-on-migrate=true

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.default-property-inclusion=non_null

wallet.initial-balance-paise=${WALLET_INITIAL_BALANCE_PAISE:100000}

logging.structured.format.console=logstash
logging.level.com.paytm.wallet=INFO

management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,prometheus
management.endpoints.web.path-mapping.health=health
management.endpoints.web.path-mapping.prometheus=metrics
management.endpoint.health.show-details=when_authorized
management.endpoint.health.probes.enabled=true
management.health.db.enabled=true
management.metrics.distribution.percentiles.http.server.requests=0.50,0.95,0.99
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}
